# Generated by Django 4.0.2 on 2022-03-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='outputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexed', models.JSONField(verbose_name='indexed')),
            ],
            options={
                'db_table': 'outputs',
                'managed': True,
            },
        ),
    ]
